### ISSUE TITLE
Type 'Future<dynamic>' is not a subtype of type 'FutureOr<List<dynamic>>' in type cast

### ISSUE THREAD

**Issue by nathanogunleye** [smartnsoft/flappy_search_bar#59]
An error seems to keep being returned despite returning a valid `Future<List<T>>` type in the `onSearch` method

```
I/flutter (12750): ‼️ SEVERE 2021-06-05 11:22:36.333049 [caller info not available] #0      SearchBarController._search (**package:flappy_search_bar_ns/flappy_search_bar_ns.dart:63:46**)
I/flutter (12750): #1      _SearchBarState._onTextChanged.<anonymous closure> (package:flappy_search_bar_ns/flappy_search_bar_ns.dart:314:29)
I/flutter (12750): #2      _SearchBarState._onTextChanged.<anonymous closure> (package:flappy_search_bar_ns/flappy_search_bar_ns.dart:312:48)
I/flutter (12750): #3      _rootRun (dart:async/zone.dart:1346:47)
I/flutter (12750): #4      _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (12750): #5      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (12750): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
I/flutter (12750): #7      _rootRun (dart:async/zone.dart:1354:13)
I/flutter (12750): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (12750): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
I/flutter (12750): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter (12750): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
I/flutter (12750): #12     
```

**Comment by nathanogunleye** [comment]
Wrong repository. Closing issue
